[project]
name = "movie-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb",
    "dotenv",
    "ipykernel",
    "langchain-chroma",
    "langchain-huggingface",
    "langchain-text-splitters",
    "langchain[google-genai]",
    "polars",
    "pre-commit",
    "ruff",
    "sentence-transformers",
    "ty",
]
